version: '3.1'

services:
  db-tpadmin:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tpadmin
      POSTGRES_USER: tpadmin
      POSTGRES_PASSWORD: tpadmin
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data: